export { default as GetInfo } from './info'
export { default as GetTypes } from './type'
export { default as deleteInfo } from './deleteinfo'
export { default as UpdateInfo } from './updateInfo'
export { default as GetVideos } from './getVideos'